"""
Repo scanner with file filtering.
Skips binary, auto-generated, and non-coding files. Source code only for initial scope.
"""
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Directory segments to skip (e.g. node_modules, .git)
SKIP_DIRS = frozenset({
    ".git", "node_modules", "__pycache__", ".venv", "venv",
    "dist", "build", "target", ".next", ".cache", "vendor",
})

# Source code extensions (initial scope — config/docs skipped for now)
ALLOWED_EXTENSIONS = frozenset({
    ".py", ".java", ".kt", ".go", ".js", ".ts", ".tsx", ".jsx",
    ".c", ".cpp", ".h", ".hpp", ".cc", ".cxx",
    ".rs", ".rb", ".php", ".swift", ".m", ".mm", ".cs", ".scala",
})

# Binary/media/auto-generated extensions to skip
SKIP_EXTENSIONS = frozenset({
    ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".svg", ".webp", ".ico",
    ".mp3", ".wav", ".ogg", ".flac", ".aac", ".m4a",
    ".mp4", ".avi", ".mov", ".mkv", ".webm", ".wmv",
    ".exe", ".dll", ".so", ".dylib", ".woff", ".woff2", ".ttf", ".eot",
    ".pyc", ".class", ".o", ".obj",
})

# Filename suffixes (check name.endswith) for auto-generated
SKIP_NAME_SUFFIXES = (".min.js", ".min.css", ".bundle.js", ".map")

# Exact filenames to skip (e.g. package-lock.json)
SKIP_FILENAMES = frozenset({
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock",
})

# Max bytes to read for binary detection
BINARY_CHECK_BYTES = 8192
# If more than this fraction of null bytes, treat as binary
NULL_BYTE_THRESHOLD = 0.05


def is_eligible_file(file_path: Path) -> bool:
    """
    Check if a file is eligible for ingestion (source code only).
    Skips config, docs, binary, auto-generated. Implement later for .json, .md, etc.
    """
    name = file_path.name
    suffix = file_path.suffix.lower()

    # Skip by exact filename
    if name in SKIP_FILENAMES:
        logger.debug("is_eligible_file skip filename file_path=%s", file_path)
        return False

    # Skip auto-generated by name suffix (e.g. foo.min.js, bar.map)
    if any(name.endswith(s) for s in SKIP_NAME_SUFFIXES):
        return False

    # Skip .env and .env.*
    if name == ".env" or name.startswith(".env."):
        logger.debug("is_eligible_file skip env file_path=%s", file_path)
        return False

    # Skip by extension
    if suffix in SKIP_EXTENSIONS:
        logger.debug("is_eligible_file skip extension file_path=%s", file_path)
        return False

    # Allow only source extensions
    if suffix not in ALLOWED_EXTENSIONS:
        logger.debug("is_eligible_file skip not in allowlist file_path=%s", file_path)
        return False

    return True


def is_binary_content(content: bytes) -> bool:
    """Check if content appears binary (null bytes or invalid utf-8)."""
    if len(content) == 0:
        return False
    sample = content[:BINARY_CHECK_BYTES]
    try:
        sample.decode("utf-8")
    except UnicodeDecodeError:
        return True
    null_count = sample.count(b"\x00")
    if len(sample) > 0 and (null_count / len(sample)) > NULL_BYTE_THRESHOLD:
        return True
    return False


def scan_directory(root: Path) -> list[Path]:
    """
    Walk directory recursively, return list of eligible file paths.
    Skips excluded dirs and files. Performs binary check on eligible files.
    """
    logger.info("scan_directory started root_path=%s", root)

    eligible: list[Path] = []
    skipped_count = 0

    for path in root.rglob("*"):
        if not path.is_file():
            continue

        # Skip if any parent is in SKIP_DIRS
        parts = path.relative_to(root).parts
        if any(p in SKIP_DIRS for p in parts):
            skipped_count += 1
            continue

        if not is_eligible_file(path):
            skipped_count += 1
            continue

        # Binary content check
        try:
            content = path.read_bytes()
        except OSError as e:
            logger.warning("scan_directory read failed path=%s error=%s", path, e)
            skipped_count += 1
            continue

        if is_binary_content(content):
            logger.debug("scan_directory skip binary path=%s", path)
            skipped_count += 1
            continue

        eligible.append(path)

    logger.info(
        "scan_directory ended root_path=%s eligible_count=%s skipped_count=%s",
        root, len(eligible), skipped_count,
    )
    return eligible
